### ISSUE TITLE
Update execa to 0.4.0

### ISSUE THREAD

**Issue by IRT-fbachmann** [jansanchez/npmrun#1]
Hi,

I love your tool, was about to program sth. like that myself. Still, had some issues in Windows 10. Those could be solved by just updating execa from 0.2.2 to 0.4.0. That version uses `cross-spawn` instead of the deprecated `cross-spawn-async` and works like a charm :)

Cheers
Flo

**Comment by jansanchez** [comment]
Hi Flo, done!
Thank you for your support!

**Comment by jansanchez** [comment]
Updated version to 1.1.0
